imports:
- path: spinnaker.jinja
- path: redis.jinja
- path: jenkins.jinja

resources:
# 1. create network/subnetwork
# 2. create storage bucket
# 3. Remove external IPs from redis and jenkins
- name: spinnaker
  type: spinnaker.jinja
  properties:
    region: us-west1
    zone: us-west1-a
    machineType: n1-standard-4
    jenkinsPassword: testing-123
    jenkinsIP: 10.240.0.201
    redisIP: 10.240.0.202
  metadata:
    dependsOn:
      - redis
      - jenkins
- name: redis
  type: redis.jinja
  properties:
    region: us-west1
    zone: us-west1-a
    machineType: n1-highmem-2
    redisIP: 10.240.0.202
- name: jenkins
  type: jenkins.jinja
  properties:
    region: us-west1
    zone: us-west1-a
    machineType: n1-standard-1
    jenkinsPassword: testing-123
    jenkinsIP: 10.240.0.201
