imports:
- path: spinnaker-stack.jinja
- path: network.jinja
- path: spinnaker.jinja
- path: scripts/spinnaker.sh
  name: spinnaker.sh
- path: redis.jinja
- path: scripts/redis.sh
  name: redis.sh
- path: jenkins.jinja
- path: scripts/jenkins.sh
  name: jenkins.sh

resources:
- type: spinnaker-stack.jinja
  name: spinnaker-stack
  properties:
    region: us-west1
    zone: us-west1-a
    ipCidrRange: 10.254.0.0/24
    spinnakerMachineType: n1-standard-4
    spinnakerIP: 10.254.0.200
    jenkinsPassword: testing-123
    jenkinsMachineType: n1-standard-1
    jenkinsIP: 10.254.0.201
    redisMachineType: n1-highmem-2
    redisIP: 10.254.0.202
